// <auto-generated />
using System;
using HealthIsWealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthIsWealth.Migrations
{
    [DbContext(typeof(HealthIsWealthContext))]
    [Migration("20260107012958_FacilViewing")]
    partial class FacilViewing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeslotID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("TimeslotID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Facility", b =>
                {
                    b.Property<int>("FacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityID"));

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("FacilityID");

                    b.HasIndex("VenueID");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.FacilitySport", b =>
                {
                    b.Property<int>("FacilitySportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilitySportID"));

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("FacilitySportID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("SportID");

                    b.ToTable("FacilitySport");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.ToTable("Review");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Timeslot", b =>
                {
                    b.Property<int>("TimeslotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeslotID"));

                    b.Property<DateTime>("EndDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("TimeslotID");

                    b.HasIndex("FacilityID");

                    b.ToTable("Timeslot");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueID");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Booking", b =>
                {
                    b.HasOne("HealthIsWealth.DatabaseTables.Timeslot", "Timeslot")
                        .WithOne("Booking")
                        .HasForeignKey("HealthIsWealth.DatabaseTables.Booking", "TimeslotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.DatabaseTables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeslot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Facility", b =>
                {
                    b.HasOne("HealthIsWealth.DatabaseTables.Venue", "Venue")
                        .WithMany("Facilities")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.FacilitySport", b =>
                {
                    b.HasOne("HealthIsWealth.DatabaseTables.Facility", "Facility")
                        .WithMany("FacilitySports")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.DatabaseTables.Sport", "Sport")
                        .WithMany("FacilitySports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Review", b =>
                {
                    b.HasOne("HealthIsWealth.DatabaseTables.Booking", null)
                        .WithOne("Review")
                        .HasForeignKey("HealthIsWealth.DatabaseTables.Review", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Timeslot", b =>
                {
                    b.HasOne("HealthIsWealth.DatabaseTables.Facility", "Facility")
                        .WithMany("Timeslots")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Booking", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Facility", b =>
                {
                    b.Navigation("FacilitySports");

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Sport", b =>
                {
                    b.Navigation("FacilitySports");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Timeslot", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HealthIsWealth.DatabaseTables.Venue", b =>
                {
                    b.Navigation("Facilities");
                });
#pragma warning restore 612, 618
        }
    }
}
