// <auto-generated />
using System;
using HealthIsWealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthIsWealth.Migrations
{
    [DbContext(typeof(HealthIsWealthContext))]
    partial class HealthIsWealthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthIsWealth.Data.HealthIsWealthUser", b =>
                {
                        .HasColumnType("int");



                        .HasColumnType("int");

                        .HasColumnType("int");


                    b.HasKey("BookingId");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            TimeslotId = 1,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            BookingId = 2,
                            TimeslotId = 2,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            BookingId = 3,
                            TimeslotId = 3,
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4"
                        });
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                        .HasColumnType("int");


                    b.ToTable("Facility");
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                        .HasColumnType("int");

                        .HasColumnType("int");

                        .HasColumnType("int");


                    b.ToTable("FacilitySport");
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");




                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            BookingId = 1,
                            Feedback = "Good facility venue has a lot of ammenities",
                            Rating = 4.5f,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            ReviewId = 2,
                            BookingId = 2,
                            Feedback = "Dirty equipments but gym has alot of machines",
                            Rating = 4f,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            ReviewId = 3,
                            BookingId = 3,
                            Feedback = "Best volleyball court ever",
                            Rating = 5f,
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4"
                        });
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");


                    b.ToTable("Sport");
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                    b.Property<DateTime>("EndDT")
                        .HasColumnType("datetime2");

                        .HasColumnType("int");

                    b.Property<DateTime>("StartDT")
                        .HasColumnType("datetime2");

                        .HasColumnType("int");


                    b.ToTable("Timeslot");
                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                        .HasColumnType("nvarchar(max)");

                        .HasColumnType("nvarchar(max)");

                        .HasColumnType("nvarchar(max)");

                        .HasColumnType("nvarchar(max)");

                        .HasColumnType("int");


                });

                {
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");


                        .HasColumnType("nvarchar(max)");





                });
#pragma warning restore 612, 618
        }
    }
}
